### ISSUE TITLE
Add Vagrant support

### ISSUE THREAD

**Issue by carlos-guzman** [rachitmehrotra1/devops-restapi#2]
As a Developer
I need a way to work locally with Vagrant
So that I can be independant of Bluemix availability

Assumptions:
- Use Vagrant and VirtualBox to build a local dev environment
- Python will be used for development

Acceptance Criteria

When I issue git clone on the project
Add I change into the project folder
And I issue vagrant up
Then I should have a complete development environment on my workstation

**Comment by rachitmehrotra1** [comment]
Hey I see that you added docker to the Vagrant file. We don't need docker for our project. Can you please remove it and update the file?

**Comment by mafshar** [comment]
Hey, since we need to use Redis, it is easy for us to leverage Docker for this purpose. I think it's a good idea to keep it.

**Comment by rachitmehrotra1** [comment]
True that.. let it be there then!
