### ISSUE TITLE
Set id when creating user

### ISSUE THREAD

**Issue by carlos-guzman** [rachitmehrotra1/devops-restapi#23]
Automatically set a user ID when creating a user

**Comment by sschweber** [comment]
I pushed this to a new branch (called set-user-id). For some reason when I'm trying to create a new user it's throwing a 500 internal server error and I'm guessing it has to do with my changes. Would someone be able to check this out and see if it's something obvious I'm missing?

**Comment by rachitmehrotra1** [comment]
@sschweber What you can do is , there must be a line saying debug true that is commented! Uncomment it and run your code, that will enable the debug mode and you can see exactly where the error is. 
I'm not at home so can't see whats causing the error, but this will surely tell you what's wrong with the code.
