### ISSUE TITLE
Root URL does not show the REST API information

### ISSUE THREAD

**Issue by rofrano** [rachitmehrotra1/devops-restapi#27]
**Bug Report:** The root URL does not show the API URL that I can call to use the API.

When I go to root URL on Bluemix: http://devchronops.mybluemix.net
Then I expect to see instructions on how to use the API

What it currently returns is:

```
{
    "name": "Meeting REST API",
    "url": "/",
    "version": "1.0"
}
```

What I expected the `url:` field to tell me what the API URL is (e.g., `/foo`), not the URL that I just called. If there is more that one URL (e.g., `/foo<id>/bar`), it should return an array of valid URLs (e.g., `['/foo', '/foo/<id>/bar']`).

There are no hard and fast rules here but you want the root URL to help the caller understand how to call the API. Swagger docs would be perfect in this situation but for now, just a hint at how to call the API is what is expected.

**Comment by rachitmehrotra1** [comment]
Reviewed the code. Looking fine.
