### ISSUE TITLE
Set up pipeline in Bluemix

### ISSUE THREAD

**Issue by sschweber** [rachitmehrotra1/devops-restapi#49]
As a developer
I need to automate the bluemix pipeline
So that our application is consistently pushed to bluemix

**Comment by carlos-guzman** [comment]
Waiting for #48 .

**Comment by rachitmehrotra1** [comment]
Since #48 is now done ( I know we need to get %age up but still it works with 84%) , i'm adding that to devops pipeline too, And then will close this issue since this is done 💃
