### ISSUE TITLE
Add endpoint to set Free time on a user

### ISSUE THREAD

**Issue by carlos-guzman** [rachitmehrotra1/devops-restapi#7]

**Comment by gnishma24** [comment]
As a User
I need an endpoint
So that I can time slots (an array) when I am available to meet

Assumptions:
We have users with their corresponding ids and names
We have Vagrant, Flask, Redis

Acceptance Criteria:
I can POST /users/id/times with a particular user with given id and set the free times.

**Comment by rachitmehrotra1** [comment]
I have updated the issue title according to what we discussed. So @gnishma24 can you please update the description accordingly

**Comment by gnishma24** [comment]
I have updated the description as we have discussed. @mafshar Please take a look at the upadated issue while coding

**Comment by mafshar** [comment]
@gnishma24 @rachitmehrotra1 shouldn't our acceptance criteria be PUT, since we are updating the free times that are already a part of the user?

**Comment by rachitmehrotra1** [comment]
@mafshar  Nope. you add more times. i.e you can be free from 5-7 then you can be free from 8-10 so you want to add that time. So you add time and not update it. And that's why we need another remove time too!

**Comment by carlos-guzman** [comment]
We could also have an endpoint to update times, but let's leave that to a different issue
