### ISSUE TITLE
Add Bluemix pipeline rules for number of instances

### ISSUE THREAD

**Issue by carlos-guzman** [rachitmehrotra1/devops-restapi#77]
As a team in JR's class
We want to be able to have 2 instances always running despite not needing them
So that we get a good grade

**Comment by carlos-guzman** [comment]
Use the service Auto-scaling and set a policy

**Comment by rachitmehrotra1** [comment]
Done. Added a rule for minimum instances to be 2 and max to be 5. And if memory usage>80% , add an instance. And remove one if memory<30%
