### ISSUE TITLE
Swagger POST /users bug

### ISSUE THREAD

**Issue by carlos-guzman** [rachitmehrotra1/devops-restapi#78]
In POST /users, the example is:

{
  "name": "string",
  "time": {
    "from": 0,
    "to": 0
  }
}

but it should be:
{
  "name": "string",
  "times": [{
    "from": 0,
    "to": 0
  }]
}

**Comment by rachitmehrotra1** [comment]
Done. Code is part of fix-swagger-stuff branch , i'll do all the other swagger changes in one branch and create a single pull request. Cleaner that way :)
