### ISSUE TITLE
Find meeting time functionality

### ISSUE THREAD

**Issue by carlos-guzman** [rachitmehrotra1/devops-restapi#8]

**Comment by gnishma24** [comment]
As a User
I need an endpoint
So that I can setup a meeting with other users

Assumptions:
We have users with their busy times

Acceptance Criteria:
I can query to URI as /meet?users=1&3&7  with the user information and it gets available time if everyone is free else no meeting time scheduled

**Comment by gnishma24** [comment]
Merged the pull request after review!
